import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthProvider";
import { SocketProvider } from "@/contexts/SocketProvider";
import WebSocketEvents from "@/components/WebSocketEvents";
import IdleAndCooldownWrapper from "@/components/IdleAndCooldownWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gicops messagerie",
  description: "Generated by voli bi gbamble kevin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" translate="no">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <SocketProvider>
            <WebSocketEvents />
            <IdleAndCooldownWrapper />
            {children}
          </SocketProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
